<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shared Report: <?php echo htmlspecialchars($report_title ?? 'Report', ENT_QUOTES, 'UTF-8'); ?></title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $base_url; ?>assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- page specific plugin styles -->
    <link rel="stylesheet" href="<?php echo $base_url; ?>assets/plugins/dataTables/dataTables.bootstrap.css"/>
    <link rel="stylesheet" href="<?php echo $base_url; ?>assets/css/font-awesome.min.css"/>
    <!-- Custom styles for this template -->
    <link href="<?php echo $base_url; ?>assets/css/custom.css" rel="stylesheet">

    <style>
        body { padding-top: 20px; padding-bottom: 20px; background-color: #f9f9f9; }
        .container { background-color: #fff; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
        .report-header { margin-bottom: 20px; }
        .export-buttons a { margin-right: 10px; }
        .timetaken-share { margin-top:15px; padding: 5px; background-color: #f0f0f0; border: 1px solid #ddd; display: inline-block;}
    </style>
</head>
<body>
    <div class="container">
        <div class="report-header">
            <h3>Report: <?php echo htmlspecialchars($report_title ?? 'Shared Query Results', ENT_QUOTES, 'UTF-8'); ?></h3>
        </div>

        <div class="export-buttons" style="margin-bottom: 15px;">
            <!-- Note: Export links will rely on $_SESSION['tableData'] being set by Share::viewReport -->
            <!-- The base for these export links needs to be the main application base, not /share/ -->
            <a target="_blank" href="<?php echo rtrim($base_url, '/'); ?>/export/csv" class="btn btn-primary btn-sm"><i class="fa fa-file-text-o"></i> Export CSV</a>
            <a target="_blank" href="<?php echo rtrim($base_url, '/'); ?>/export/excel" class="btn btn-primary btn-sm"><i class="fa fa-file-excel-o"></i> Export Excel</a>
        </div>

        <div id="shared_table_data">
            <?php echo $table_data_html; // This comes from Presenter::listTableData ?>
        </div>

        <?php if (isset($timetaken) && $timetaken): ?>
            <div class="timetaken-share">Time Taken: <strong><?php echo htmlspecialchars($timetaken, ENT_QUOTES, 'UTF-8'); ?></strong> second(s)</div>
        <?php endif; ?>

        <hr>
        <footer class="text-center">
            <p>&copy; QueryCloud Shared Report</p>
        </footer>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?php echo $base_url; ?>assets/js/jquery-1.10.2.js"></script>
    <script src="<?php echo $base_url; ?>assets/js/bootstrap.min.js"></script>

    <!-- page specific plugin scripts -->
    <script src="<?php echo $base_url; ?>assets/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="<?php echo $base_url; ?>assets/plugins/dataTables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            // Initialize DataTable for the shared report table
            // The table generated by Presenter::listTableData already has appropriate classes.
            if ($('#shared_table_data table').length > 0) {
                $('#shared_table_data table').dataTable({
                    sPaginationType: "full_numbers",
                    bLengthChange: true,
                    iDisplayLength: 10, // Or a configurable default
                    bAutoWidth: false,
                    scrollX: 400 // Enable horizontal scrolling if needed
                });
            }
        });
    </script>
</body>
</html>
